# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cb8eb8ee04ab02c330fd536fe19d3bad"
name = "sync app"
handle = "sync-app-21"
application_url = "https://b7a9-176-37-57-140.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://b7a9-176-37-57-140.ngrok-free.app/auth/callback",
  "https://b7a9-176-37-57-140.ngrok-free.app/auth/shopify/callback",
  "https://b7a9-176-37-57-140.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
